# -*- coding: utf-8 -*-
"""PengolahanCitraDigital3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOcB_pPHA5J23nCsulbFEwcVMeTn0YxK
"""

import matplotlib.pyplot as plt
plt.plot((2,4,6,8))
plt.title("grafik praktik pcd")
plt.xlabel("sumbu x")
plt.ylabel("sumbu y")
plt.show()

plt.plot((0,1,2,3), (4,2,6,4))
plt.title("grafik praktik pcd")
plt.xlabel("sumbu x")
plt.ylabel("sumbu y")
plt.show()

plt.plot((0,1,2,3),(4,2,6,4))
plt.plot((1,2,3,4),(2,3,4,5))
plt.title("grafikvpraktik pcd")
plt.xlabel("sumbu x")
plt.ylabel("sumbu y")
plt.show()

fig, ax = plt.subplots(1,2, figsize=(10,5))

ax[0].plot([2,4,6,8])
ax[0].set_title("grafik pertama")

ax[1].plot([2,6,4,8])
ax[1].set_title("grafik kedua")

plt.tight_layout()
plt.show()

fig, ax = plt.subplots(2,2, figsize=(10,5))

ax[0,0].plot([1,2,3,4])
ax[0,0].set_title("ax[0,0]")

ax[0,1].plot([4,3,2,1])
ax[0,1].set_title("ax[0,1]")

ax[1,0].plot([1,1,2,2])
ax[1,0].set_title("ax[1,0]")

ax[1,1].plot([2,2,1,1])
ax[1,1].set_title("ax[1,1]")

plt.tight_layout()
plt.show()

import numpy as np
fig, ax = plt.subplots(2,2, figsize=(10,8))

ax[0,0].bar(['A','B','C','D'], [3,7,2,5], color=['red','green','yellow', 'blue'])
ax[0,0].set_title('Bar Chart')
ax[0,0].set_xlabel('Categories')
ax[0,0].set_ylabel('Values')

#lineplot
ax[0,0].plot([1,2,3,4,5], [1,4,2,5,3], marker='o', linestyle='-', color='purple')
ax[0,0].set_title('line plot')
ax[0,0].set_xlabel('nilai x')
ax[0,0].set_ylabel('nilai y')

#histogram
ax[1,0].hist(np.random.random(1000), bins=20, color='skyblue',edgecolor='black')
ax[1,0].set_title('histogram')
ax[1,0].set_xlabel('nilai')
ax[1,0].set_ylabel('frekuensi')

#2D
im = ax[1,1].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
ax[1,1].set_title('Gambar 2D')
plt.colorbar(im)

plt.tight_layout()
plt.show()

layout = [
    ['A', 'B'],
    ['C', 'D']
]

fig, ax = plt.subplot_mosaic(layout, figsize=(10,8))

ax['A'].plot([1,2,3,4,5], [1,4,2,5,3], marker='o', linestyle='-', color='purple')
ax['A'].set_title('line plot')

ax['B'].bar(['A','B','C','D'], [3,7,2,5], color=['red','green','yellow', 'blue'])
ax['B'].set_title('Bar Chart')

ax['C'].hist(np.random.random(1000), bins=20, color='skyblue',edgecolor='black')
ax['C'].set_title('histogram')

ax['D'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
ax['D'].set_title('Gambar 2D')
plt.tight_layout()
plt.show()

layout = [
    ['A', 'B'],
    ['C', 'C']
]

fig, ax = plt.subplot_mosaic(layout, figsize=(10,8))

ax['A'].plot([1,2,3,4,5], [1,4,2,5,3], marker='o', linestyle='-', color='purple')
ax['A'].set_title('line plot')

ax['B'].bar(['A','B','C','D'], [3,7,2,5], color=['red','green','yellow', 'blue'])
ax['B'].set_title('Bar Chart')

ax['C'].hist(np.random.random(1000), bins=20, color='skyblue',edgecolor='black')
ax['C'].set_title('histogram')

#ax['D'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
#ax['D'].set_title('Gambar 2D')
plt.tight_layout()
plt.show()

layout = [
    ['A', 'B'],
    ['C', 'B']
]

fig, ax = plt.subplot_mosaic(layout, figsize=(10,8))

ax['A'].plot([1,2,3,4,5], [1,4,2,5,3], marker='o', linestyle='-', color='purple')
ax['A'].set_title('line plot')

ax['B'].bar(['A','B','C','D'], [3,7,2,5], color=['red','green','yellow', 'blue'])
ax['B'].set_title('Bar Chart')

ax['C'].hist(np.random.random(1000), bins=20, color='skyblue',edgecolor='black')
ax['C'].set_title('histogram')

#ax['D'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
#ax['D'].set_title('Gambar 2D')
plt.tight_layout()
plt.show()

layout = [
    ['A','.','B'],
    ['.','C', '.'],
    ['D','.','E']
]

fig, ax = plt.subplot_mosaic(layout, figsize=(10,8))

ax['A'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
ax['A'].set_title('Gambar 1')

ax['B'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
ax['B'].set_title('Gambar 2')

ax['C'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
ax['C'].set_title('Gambar 3')

ax['D'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
ax['D'].set_title('Gambar 5')

ax['E'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
ax['E'].set_title('Gambar 6')
plt.tight_layout()
plt.show()

def identity_axes(ax_dict, fontsize=48):
  kw = dict(ha='center', va='center', fontsize=fontsize)
  for ax in ax_dict.values():
    ax.text(0.5, 0.5, "ax=plt.gca()", transform=ax.transAxes, **kw)
  return ax_dict
layout = [
    ['A', 'B'],
    ['C', 'C']
]

fig, ax = plt.subplot_mosaic(layout, figsize=(10,8))

ax['A'].plot([1,2,3,4,5], [1,4,2,5,3], marker='o', linestyle='-', color='purple')
ax['A'].set_title('line plot')

ax['B'].bar(['A','B','C','D'], [3,7,2,5], color=['red','green','yellow', 'blue'])
ax['B'].set_title('Bar Chart')

ax['C'].hist(np.random.random(1000), bins=20, color='skyblue',edgecolor='black')
ax['C'].set_title('histogram')

#ax['D'].imshow(np.random.random((10,10)), cmap='plasma',interpolation='nearest')
#ax['D'].set_title('Gambar 2D')
plt.tight_layout()
plt.show()